# Generated by Django 3.2.5 on 2021-07-09 09:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('enterprise', models.CharField(max_length=100)),
                ('first_name_client', models.CharField(max_length=100)),
                ('last_name_client', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=200)),
                ('population', models.BigIntegerField()),
                ('telephone_number', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('zip_code', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('credit_card', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)])),
                ('client_img_name', models.CharField(max_length=50)),
                ('client_img_img', models.ImageField(upload_to='clients_images/')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('product_name', models.CharField(max_length=150)),
                ('description_product', models.CharField(max_length=300)),
                ('supplier_code', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('unity_price', models.BigIntegerField()),
                ('unit_in_stock', models.BigIntegerField()),
                ('prodcuts_img_name', models.CharField(max_length=50)),
                ('prodcuts_img_img', models.ImageField(upload_to='prodcuts_images/')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('order_number', models.BigIntegerField()),
                ('client_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image_storage.client')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image_storage.products')),
            ],
        ),
    ]
