# Generated by Django 3.2.5 on 2021-07-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_storage', '0002_alter_client_client_img_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_img_img',
            field=models.ImageField(upload_to='clients_images/'),
        ),
    ]
