# Generated by Django 3.2.4 on 2021-06-22 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='credit_card',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='population',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone_number',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='supplier_code',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='unit_in_stock',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='unity_price',
            field=models.BigIntegerField(),
        ),
    ]
